name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# permissions:
#   contents: read

jobs:
  generate-seed:
    name: Generate random seed
    runs-on: ubuntu-latest
    outputs:
      seed: ${{ steps.seed_generator.outputs.seed }}
    steps:
      - id: seed_generator
        run: echo "::set-output name=seed::$(shuf -i 0-99999 -n 1)"

  rspec:
    name: Ruby ${{matrix.ruby-version}}
    runs-on: ubuntu-latest
    needs: [ generate-seed ]
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
#          - 2.7
#          - 3.0
#          - 3.1
          - 3.2
#          - head
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: RSpec
        run: bundle exec rspec --seed ${{ needs.generate-seed.outputs.seed }}
